# docker compose up -d

version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    depends_on:
#      - user-service
#      - authentication-service

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pass
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

#  discovery-server:
#    image: huyngo1110/discovery-server:latest
#    container_name: discovery-server
#    pull_policy: always
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILE_ACTIVE=docker
#    depends_on:
#      - zipkin
#
#  api-gateway:
#    image: huyngo1110/api-gateway:latest
#    container_name: api-gateway
#    pull_policy: always
#    ports:
#      - "8181:8080"
#    expose:
#      - "8181"
#    environment:
#      - SPRING_PROFILE_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRING_SECURITY= TRACE
#    depends_on:
#      - zipkin
#      - discovery-server
#
#  authentication-service:
#    image: huyngo1110/authentication-service:latest
#    container_name: authentication-service
#    pull_policy: always
#    environment:
#      - SPRING_PROFILE_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRING_SECURITY= TRACE
#    depends_on:
#      - zipkin
#      - discovery-server
#      - api-gateway
#
#  user-service:
#    image: huyngo1110/user-service:latest
#    container_name: user-service
#    pull_policy: always
#    environment:
#      - SPRING_PROFILE_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRING_SECURITY= TRACE
#    depends_on:
#      - zipkin
#      - discovery-server
#      - api-gateway
